### PR TITLE
Add cobra CLI

### PR DESCRIPTION
**Pull request by maruina**
- Add cobra to implement the CLI with the following 2 commands
	- serve: to start go-inbrabin with options like port number, etc.
	- version: just print the version and exit
- `cmd/root.go` is what happens when you just execute `./go-infrabin`
- This is a breaking change so the plan it to bump the release to 2.x.x
- Change the Makefile to print the git short commit SHA as version.
- To avoid having to bind every individual flag with
```
viper.BindPFlag("port", serverCmd.Flags().Lookup("port"))
```
we use `viper.BindPFlags(serveCmd.Flags())`. This mean every viper variable is in the same format as its cobra counterpart, so for example we have an `max-delay` instead of `maxDelay`.

### CODE REVIEW

**Comment by maruina** [comment]
@Smirl what are your thoughts on the commands? Do you think we need more? Though on the `serve` one? I prefer it over `server`, like they do for example in Hugo.

**Comment by maruina** [comment]
Broke this test
```
2020/11/15 13:34:06 gRPC grpc server stopped
    grpc_test.go:70: Shutdown didn't take expected time. Took 201 milliseconds
panic: test timed out after 10m0s
```
but I don't get why it doesn't set the timeout with `Viper.Set()`.

**Comment by maruina** [comment]
Fixed the test but I'm not 100% sure it's the right approach.

**Review by Smirl — APPROVED** [review]
Agreed that this approach will be a big improvement. However, not having config available unless using the cli is a bit of an issue (as seen in `grpc_test.go`).

This should be a major bump as it changes the way the app needs to be started. Future improvements to config can be minor/patches.

**Comment by maruina** [comment]
@Smirl haven't merged this yet because I don't like the approach. As we discussed, the config should be part of the package and then we should overwrite it with the CLI. I will do a little more investigation.

**Comment by maruina** [comment]
Done is https://github.com/maruina/go-infrabin/pull/62

**Pull request closed without merging**
